
# /O FILE
(globals
   version=1
   io_order = clockwise
   space = 5
   total_edge=8
)

(iopad

    (topleft
      (inst name="CornerCell1" cell=CORNERC offset=0 orientation=R180 place_status=fixed)
    )

    (top

      (inst name="pcpi_insn[0]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[1]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[2]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[3]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[4]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[5]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[6]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[7]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[8]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[9]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[10]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[11]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[12]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[13]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[14]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[15]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[16]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[17]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[18]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[19]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[20]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[21]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[22]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[23]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[24]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[25]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[26]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[27]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[28]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[29]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[30]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_insn[31]" cell=YA2GSC place_status=fixed)

    )

    (topright
      (inst name="CornerCell2" cell=CORNERC offset=0 orientation=R90 place_status=fixed)
    )

    (right

      (inst name="pcpi_rs1[0]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[1]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[2]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[3]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[4]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[5]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[6]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[7]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[8]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[9]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[10]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[11]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[12]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[13]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[14]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[15]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[16]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[17]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[18]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[19]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[20]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[21]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[22]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[23]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[24]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[25]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[26]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[27]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[28]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[29]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[30]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs1[31]" cell=YA2GSC place_status=fixed)

      (inst name="pcpi_rs2[0]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[1]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[2]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[3]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[4]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[5]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[6]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[7]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[8]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[9]"  cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[10]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[11]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[12]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[13]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[14]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[15]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[16]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[17]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[18]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[19]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[20]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[21]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[22]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[23]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[24]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[25]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[26]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[27]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[28]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[29]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[30]" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_rs2[31]" cell=YA2GSC place_status=fixed)

    )

    (bottomright
      (inst name="CornerCell3" cell=CORNERC offset=0 orientation=R0 place_status=fixed)
    )

    (bottom

      (inst name="pcpi_rd[0]"  cell=XMC place_status=fixed)
      (inst name="pcpi_rd[1]"  cell=XMC place_status=fixed)
      (inst name="pcpi_rd[2]"  cell=XMC place_status=fixed)
      (inst name="pcpi_rd[3]"  cell=XMC place_status=fixed)
      (inst name="pcpi_rd[4]"  cell=XMC place_status=fixed)
      (inst name="pcpi_rd[5]"  cell=XMC place_status=fixed)
      (inst name="pcpi_rd[6]"  cell=XMC place_status=fixed)
      (inst name="pcpi_rd[7]"  cell=XMC place_status=fixed)
      (inst name="pcpi_rd[8]"  cell=XMC place_status=fixed)
      (inst name="pcpi_rd[9]"  cell=XMC place_status=fixed)
      (inst name="pcpi_rd[10]" cell=XMC place_status=fixed)
      (inst name="pcpi_rd[11]" cell=XMC place_status=fixed)
      (inst name="pcpi_rd[12]" cell=XMC place_status=fixed)
      (inst name="pcpi_rd[13]" cell=XMC place_status=fixed)
      (inst name="pcpi_rd[14]" cell=XMC place_status=fixed)
      (inst name="pcpi_rd[15]" cell=XMC place_status=fixed)
      (inst name="pcpi_rd[16]" cell=XMC place_status=fixed)
      (inst name="pcpi_rd[17]" cell=XMC place_status=fixed)
      (inst name="pcpi_rd[18]" cell=XMC place_status=fixed)
      (inst name="pcpi_rd[19]" cell=XMC place_status=fixed)
      (inst name="pcpi_rd[20]" cell=XMC place_status=fixed)
      (inst name="pcpi_rd[21]" cell=XMC place_status=fixed)
      (inst name="pcpi_rd[22]" cell=XMC place_status=fixed)
      (inst name="pcpi_rd[23]" cell=XMC place_status=fixed)
      (inst name="pcpi_rd[24]" cell=XMC place_status=fixed)
      (inst name="pcpi_rd[25]" cell=XMC place_status=fixed)
      (inst name="pcpi_rd[26]" cell=XMC place_status=fixed)
      (inst name="pcpi_rd[27]" cell=XMC place_status=fixed)
      (inst name="pcpi_rd[28]" cell=XMC place_status=fixed)
      (inst name="pcpi_rd[29]" cell=XMC place_status=fixed)
      (inst name="pcpi_rd[30]" cell=XMC place_status=fixed)
      (inst name="pcpi_rd[31]" cell=XMC place_status=fixed)

    )

    (bottomleft
      (inst name="CornerCell4" cell=CORNERC offset=0 orientation=R270 place_status=fixed)
    )

    (left

      (inst name="pcpi_valid" cell=YA2GSC place_status=fixed)
      (inst name="pcpi_wr"    cell=XMC    place_status=fixed)
      (inst name="pcpi_wait"  cell=XMC    place_status=fixed)
      (inst name="pcpi_ready" cell=XMC    place_status=fixed)

      (inst name="VDD"  cell=VCCKC   place_status=fixed)
      (inst name="GND"  cell=GNDKC   place_status=fixed)
      (inst name="VDDO" cell=VCC3IOC place_status=fixed)
      (inst name="GNDO" cell=GNDIOC  place_status=fixed)

    )
)
